"""Template: tests for an external agent adapter.

All tests mock subprocess.run so the real guest CLI is never invoked.
Copy and adapt for your own adapter.
"""

from __future__ import annotations

import subprocess
from typing import Any
from unittest.mock import patch

import pytest

# CUSTOMIZE: import your adapter module.
from agent_context.hermes_agent import HermesAgent


def _fake_completed_process(
    *, returncode: int = 0, stdout: str = "", stderr: str = ""
) -> subprocess.CompletedProcess:
    return subprocess.CompletedProcess(
        args=["guest"], returncode=returncode, stdout=stdout, stderr=stderr
    )


def _make_agent() -> HermesAgent:
    return HermesAgent(name="Test Agent", max_turns=5)


# ---------------------------------------------------------------------------
# Protocol compliance
# ---------------------------------------------------------------------------


def test_is_base_external_agent_subclass():
    from agno.agents.base import BaseExternalAgent

    agent = _make_agent()
    assert isinstance(agent, BaseExternalAgent)


def test_framework_label():
    agent = _make_agent()
    assert agent.framework == "hermes"


def test_get_id_autogenerated_from_name():
    agent = HermesAgent(name="Test Agent")
    assert agent.get_id() != ""
    assert agent.id is not None


def test_implements_adapter_hooks():
    agent = _make_agent()
    assert callable(getattr(agent, "_arun_adapter", None))
    assert callable(getattr(agent, "_arun_adapter_stream", None))


# ---------------------------------------------------------------------------
# Command building
# ---------------------------------------------------------------------------


def test_build_command_basic():
    agent = _make_agent()
    cmd = agent._build_command("hello", hermes_session_id=None)  # type: ignore
    assert cmd[0] == "hermes"
    assert "-q" in cmd and "hello" in cmd
    assert "--resume" not in cmd


def test_build_command_with_resume():
    agent = _make_agent()
    cmd = agent._build_command("hello", hermes_session_id="abc-123")  # type: ignore
    idx = cmd.index("--resume")
    assert cmd[idx + 1] == "abc-123"


# ---------------------------------------------------------------------------
# Session ID parsing
# ---------------------------------------------------------------------------


def test_parse_session_id_found():
    assert HermesAgent._parse_session_id("session_id: abc-123\n") == "abc-123"


def test_parse_session_id_missing():
    assert HermesAgent._parse_session_id("") is None


# ---------------------------------------------------------------------------
# Non-streaming adapter
# ---------------------------------------------------------------------------


@pytest.mark.anyio
async def test_arun_adapter_returns_stdout():
    agent = _make_agent()
    fake = _fake_completed_process(stdout="hello world", stderr="session_id: s1\n")

    with patch("agent_context.hermes_agent.subprocess.run", return_value=fake):
        result = await agent._arun_adapter("hi")

    assert result == "hello world"


@pytest.mark.anyio
async def test_arun_adapter_stores_session_mapping():
    agent = _make_agent()
    fake = _fake_completed_process(stdout="ok", stderr="session_id: s1\n")

    with patch("agent_context.hermes_agent.subprocess.run", return_value=fake):
        await agent._arun_adapter("hi", session_id="agno-1")

    assert agent._hermes_session_ids["agno-1"] == "s1"


@pytest.mark.anyio
async def test_arun_adapter_raises_on_nonzero_exit():
    agent = _make_agent()
    fake = _fake_completed_process(returncode=1, stderr="bang")

    with patch("agent_context.hermes_agent.subprocess.run", return_value=fake):
        with pytest.raises(RuntimeError, match="bang"):
            await agent._arun_adapter("hi")


# ---------------------------------------------------------------------------
# Streaming adapter
# ---------------------------------------------------------------------------


@pytest.mark.anyio
async def test_arun_adapter_stream_emits_content_event():
    agent = _make_agent()
    fake = _fake_completed_process(stdout="hello", stderr="session_id: s1\n")

    with patch("agent_context.hermes_agent.subprocess.run", return_value=fake):
        events = [e async for e in agent._arun_adapter_stream("hi", run_id="r1")]

    assert len(events) == 1
    assert events[0].content == "hello"


@pytest.mark.anyio
async def test_arun_adapter_stream_raises_on_nonzero_exit():
    agent = _make_agent()
    fake = _fake_completed_process(returncode=1, stderr="boom")

    with patch("agent_context.hermes_agent.subprocess.run", return_value=fake):
        with pytest.raises(RuntimeError, match="boom"):
            async for _ in agent._arun_adapter_stream("hi"):
                pass


# ---------------------------------------------------------------------------
# Session isolation
# ---------------------------------------------------------------------------


@pytest.mark.anyio
async def test_different_sessions_do_not_cross_bleed():
    agent = _make_agent()
    fake_a = _fake_completed_process(stdout="a", stderr="session_id: s-a\n")
    fake_b = _fake_completed_process(stdout="b", stderr="session_id: s-b\n")

    with patch("agent_context.hermes_agent.subprocess.run", return_value=fake_a):
        await agent._arun_adapter("hi", session_id="agno-a")
    with patch("agent_context.hermes_agent.subprocess.run", return_value=fake_b):
        await agent._arun_adapter("hi", session_id="agno-b")

    assert agent._hermes_session_ids["agno-a"] == "s-a"
    assert agent._hermes_session_ids["agno-b"] == "s-b"


# ---------------------------------------------------------------------------
# End-to-end via public arun API
# ---------------------------------------------------------------------------


@pytest.mark.anyio
async def test_arun_non_stream_returns_run_output():
    agent = _make_agent()
    fake = _fake_completed_process(stdout="final", stderr="session_id: s1\n")

    with patch("agent_context.hermes_agent.subprocess.run", return_value=fake):
        output = await agent.arun("hi")  # type: ignore[func-returns-value]

    from agno.run.base import RunStatus

    assert output.content == "final"
    assert output.status == RunStatus.COMPLETED
